# General parameters
dataset: Allstate_Claims
model_name: VIME # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM, ModelTree
                # MLP, TabNet, VIME, TabTransformer, RLN, DNFNet, STG, NAM, DeepFM, SAINT
objective: probabilistic_regression # Don't change (regression , probabilistic_regression)
# optimize_hyperparameters: True

y_distribution : skewed

# GPU parameters
use_gpu: True
gpu_ids: [0, 1]
data_parallel: False

# Optuna parameters - https://optuna.org/
n_trials: 100
direction: maximize  # maximize - class, minimize - reg

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221 # Don't change

# Preprocessing parameters
scale: True
target_encode: False
one_hot_encode: True
ordinal_encode : False  

# Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 100
logging_period: 100

# About the data
num_classes: 1  # always 1 for regression
num_features: 131  #without target variable
nominal_idx : [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
 21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,
 41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,
 61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,
 81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,
 101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116]
#ordinal_idx : []
dropna_idx : [0]
#miss_cat_idx : []
#miss_num_idx : []

# cat_dims: will be automatically set.
#cat_dims: [9, 16, 7, 15, 6, 5, 2, 42]