parameters: {
  Boston: {
    RandomForest: {'max_depth': 12, 'n_estimators': 59},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 5, 'lambda_l1': 6.462507588741124e-08, 'lambda_l2': 2.0301223361477955e-07, 'learning_rate': 0.18929487455750107, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.19271919948138766, 'max_depth': 5, 'l2_leaf_reg': 2.317875889255283, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {'p_m': 0.8681902625624857, 'alpha': 1.1876583336706839, 'K': 10, 'beta': 0.11595464794430743
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 200, 'maxleaf': 128, 'loss_de': 3, 'loss_dr': 0.9},
    TabNet: {'n_d': 52, 'n_steps': 6, 'gamma': 1.050413339231028, 'cat_emb_dim': 2, 'n_independent': 3, 
             'n_shared': 3, 'momentum': 0.07118274530382916, 'mask_type': 'sparsemax', 'n_a': 52, 
             'cat_idxs': [], 'cat_dims': [], 'device_name': device(type='cuda')},
    TabTransformer: {'dim': 256, 'depth': 2, 'heads': 4, 'weight_decay': -1, 'learning_rate': -3, 'dropout': 0.5},
    SAINT: {'dim': 128, 'depth': 3, 'heads': 2, 'dropout': 0.1},
  },
  Socmob: {
    RandomForest: {'max_depth': 12, 'n_estimators': 32},
    XGBoost: {
      'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'
    },
    LightGBM: {'num_leaves': 28, 'lambda_l1': 0.13005278846014845, 'lambda_l2': 0.0023669205288624584, 'learning_rate': 0.2766492871149721, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.16207815622453, 'max_depth': 9, 'l2_leaf_reg': 0.8165913346565579, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {
      'p_m': 0.5282587749099882, 'alpha': 6.951871296200623, 'K': 10, 'beta': 0.708458329934869
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 100, 'maxleaf': 128, 'loss_de': 6, 'loss_dr': 0.9},
    TabNet: {
      'n_d': 29, 'n_steps': 7, 'gamma': 1.7740361293896294, 'cat_emb_dim': 3, 'n_independent': 4, 
      'n_shared': 5, 'momentum': 0.13153313619311685, 'mask_type': 'sparsemax', 'n_a': 29, 'cat_idxs': [], 
      'cat_dims': [], 'device_name': device(type='cuda')
    },
    TabTransformer: {'dim': 256, 'depth': 2, 'heads': 4, 'weight_decay': -1, 'learning_rate': -3, 'dropout': 0.5},
    SAINT: {'dim': 32, 'depth': 12, 'heads': 4, 'dropout': 0.7},
  },
  Sensory: {
    RandomForest: {'max_depth': 7, 'n_estimators': 65},
    XGBoost: {'max_depth': 9, 'alpha': 0.00021827408412994793, 'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 1377, 'lambda_l1': 0.0696978844641706, 'lambda_l2': 3.3148666906051775e-08, 'learning_rate': 0.2994482044374772, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.1690834325576087, 'max_depth': 5, 'l2_leaf_reg': 0.9479202249624208, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {
      'p_m': 0.5582176534331378, 'alpha': 9.613597687648259, 'K': 20, 'beta': 0.49652097114986354
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 200, 'maxleaf': 64, 'loss_de': 3, 'loss_dr': 0.9},
    TabNet: {
      'n_d': 29, 'n_steps': 7, 'gamma': 1.7740361293896294, 'cat_emb_dim': 3, 'n_independent': 4, 
      'n_shared': 5, 'momentum': 0.13153313619311685, 'mask_type': 'sparsemax', 'n_a': 29, 'cat_idxs': [], 
      'cat_dims': [], 'device_name': device(type='cuda')
    },
    TabTransformer: {'dim': 256, 'depth': 12, 'heads': 8, 'weight_decay': -5, 'learning_rate': -3, 'dropout': 0.5},
    SAINT: {'dim': 32, 'depth': 12, 'heads': 4, 'dropout': 0.7},
  },
  Moneyball: {
    RandomForest: {'max_depth': 11, 'n_estimators': 78},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 5, 'lambda_l1': 2.7455845652197672e-05, 'lambda_l2': 2.2212195400044564e-06, 'learning_rate': 0.23328350197161804, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.23144658145987732, 'max_depth': 5, 'l2_leaf_reg': 11.220279191086606, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {
      'p_m': 0.14534935488077078, 'alpha': 1.3731029290912213, 'K': 10, 'beta': 0.1392277141225916
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 200, 'maxleaf': 128, 'loss_de': 2, 'loss_dr': 0.7},
    TabNet: {
      'n_d': 55, 'n_steps': 4, 'gamma': 1.3548678767620057, 'cat_emb_dim': 3, 'n_independent': 5, 
      'n_shared': 1, 'momentum': 0.24488147555334566, 'mask_type': 'sparsemax', 'n_a': 55, 'cat_idxs': [], 
      'cat_dims': [], 'device_name': device(type='cuda')
    },
    TabTransformer: {'dim': 64, 'depth': 12, 'heads': 2, 'weight_decay': -1, 'learning_rate': -3, 'dropout': 0.1},
    SAINT: {'dim': 128, 'depth': 3, 'heads': 4, 'dropout': 0.2},
  },
  Black_Friday: {
    RandomForest: {'max_depth': 12, 'n_estimators': 84},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 175, 'lambda_l1': 9.25559291746777e-05, 'lambda_l2': 0.0001446789550254764, 'learning_rate': 0.11949803217855552, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.27190280014211804, 'max_depth': 10, 'l2_leaf_reg': 7.000170831256405, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100,},
    VIME: {
      'p_m': 0.5855804183944784, 'alpha': 7.637309503741228, 'K': 15, 'beta': 4.80545994193209
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 100, 'maxleaf': 64, 'loss_de': 3, 'loss_dr': 0.9},
    TabNet: {
      'n_d': 27, 'n_steps': 8, 'gamma': 1.4334266342650124, 'cat_emb_dim': 2, 'n_independent': 4, 
      'n_shared': 1, 'momentum': 0.009662335630523301, 'mask_type': 'entmax'
    },
    TabTransformer: {'dim': 128, 'depth': 2, 'heads': 8, 'weight_decay': -6, 'learning_rate': -3, 'dropout': 0.3},
    SAINT: {'dim': 128, 'depth': 3, 'heads': 2, 'dropout': 0.3},
  },
  SAT11: {
    RandomForest: {'max_depth': 12, 'n_estimators': 79},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 2284, 'lambda_l1': 3.914476960095439e-06, 'lambda_l2': 3.911994444340022e-08, 'learning_rate': 0.1352137050764449, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.2513335517632794, 'max_depth': 10, 'l2_leaf_reg': 11.635106678314445, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {
      'p_m': 0.8537536712438457, 'alpha': 0.11047685312602139, 'K': 20, 'beta': 6.833123020518896
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 100, 'maxleaf': 64, 'loss_de': 6, 'loss_dr': 0.9},
    TabNet: {
      'n_d': 43, 'n_steps': 9, 'gamma': 1.751938929868293, 'cat_emb_dim': 2, 'n_independent': 4, 
      'n_shared': 3, 'momentum': 0.10895265262047434, 'mask_type': 'entmax', 'n_a': 43, 'cat_idxs': [], 
      'cat_dims': [], 'device_name': device(type='cuda')
    },
    TabTransformer: {'dim': 128, 'depth': 1, 'heads': 4, 'weight_decay': -5, 'learning_rate': -3, 'dropout': 0.1},
    SAINT: {'dim': 128, 'depth': 2, 'heads': 2, 'dropout': 0.8},
  },
  Diamonds: {
    RandomForest: {'max_depth': 12, 'n_estimators': 79},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 209, 'lambda_l1': 3.0613110141815473e-07, 'lambda_l2': 5.399870829907466, 'learning_rate': 0.07696857618292431, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.20916344261734382, 'max_depth': 9, 'l2_leaf_reg': 1.612289068593731, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100,},
    VIME: {'p_m': 0.7339898965512561, 'alpha': 4.489275820815092, 'K': 10, 'beta': 0.35927548131057563
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 100, 'maxleaf': 128, 'loss_de': 2, 'loss_dr': 0.9},
    TabNet: {'n_d': 41, 'n_steps': 10, 'gamma': 1.1224322533685716, 'cat_emb_dim': 1, 'n_independent': 5, 'n_shared': 4, 
             'momentum': 0.32030669497532765, 'mask_type': 'entmax'},
    TabTransformer: {'dim': 32, 'depth': 1, 'heads': 8, 'weight_decay': -2, 'learning_rate': -3, 'dropout': 0.5},
    SAINT: {'dim': 32, 'depth': 3, 'heads': 4, 'dropout': 0.3},
  },
  House_Prices_Nominal: {
    RandomForest: {'max_depth': 12, 'n_estimators': 65},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 9, 'lambda_l1': 0.30721778041342623, 'lambda_l2': 0.6607690923269641, 'learning_rate': 0.12674081976447796, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.1643548593541169, 'max_depth': 5, 'l2_leaf_reg': 1.2677797570808662, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {'p_m': 0.6189603587975631, 'alpha': 2.269328779984874, 'K': 20, 'beta': 0.20886579322966808},
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 200, 'maxleaf': 64, 'loss_de': 5, 'loss_dr': 0.9},
    TabNet: {'n_d': 41, 'n_steps': 10, 'gamma': 1.1224322533685716, 'cat_emb_dim': 1, 'n_independent': 5, 'n_shared': 4, 
             'momentum': 0.32030669497532765, 'mask_type': 'entmax'},
    TabTransformer: {'dim': 128, 'depth': 3, 'heads': 2, 'weight_decay': -4, 'learning_rate': -3, 'dropout': 0.5},
    SAINT: {'dim': 128, 'depth': 3, 'heads': 2, 'dropout': 0.1},
  },
  Mercedes_Benz: {
    RandomForest: {'max_depth': 4, 'n_estimators': 79},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 4, 'lambda_l1': 0.07219206791881717, 'lambda_l2': 0.012323436994039426, 'learning_rate': 0.17660748162875636, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.15690288841764996, 'max_depth': 4, 'l2_leaf_reg': 0.9272912202250073, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {
      'p_m': 0.19543335210332746, 'alpha': 9.619143087097799, 'K': 2, 'beta': 6.291092231131599
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 200, 'maxleaf': 64, 'loss_de': 4, 'loss_dr': 0.9},
    TabNet: {'n_d': 41, 'n_steps': 10, 'gamma': 1.1224322533685716, 'cat_emb_dim': 1, 'n_independent': 5, 'n_shared': 4, 
             'momentum': 0.32030669497532765, 'mask_type': 'entmax'},
    TabTransformer: {'dim': 128, 'depth': 3, 'heads': 2, 'weight_decay': -4, 'learning_rate': -3, 'dropout': 0.5},
    SAINT: {'dim': 64, 'depth': 3, 'heads': 2, 'dropout': 0.2},
  },
  Allstate_Claims: {
    RandomForest: {'max_depth': 12, 'n_estimators': 71},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 110, 'lambda_l1': 3.51200774262605e-07, 'lambda_l2': 4.2024870289047104e-07, 'learning_rate': 0.0801014517726726, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.1795138393400397, 'max_depth': 9, 'l2_leaf_reg': 1.2027587972069935, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {'p_m': 0.49872702063803265, 'alpha': 3.314726834416219, 'K': 3, 'beta': 8.43839397201792
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 200, 'maxleaf': 64, 'loss_de': 2, 'loss_dr': 0.9},
    TabNet: {'n_d': 41, 'n_steps': 10, 'gamma': 1.1224322533685716, 'cat_emb_dim': 1, 'n_independent': 5, 'n_shared': 4, 
             'momentum': 0.32030669497532765, 'mask_type': 'entmax'},
    TabTransformer: {'dim': 32, 'depth': 2, 'heads': 8, 'weight_decay': -2, 'learning_rate': -4, 'dropout': 0.1},
    SAINT: {'dim': 128, 'depth': 3, 'heads': 2, 'dropout': 0.1},
  },
  Brazillian_Houses: {
    RandomForest: {'max_depth': 12, 'n_estimators': 5},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 2947, 'lambda_l1': 0.104639036235553, 'lambda_l2': 0.0004284066050402789, 'learning_rate': 0.29875974159690666, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.2370947635349344, 'max_depth': 11, 'l2_leaf_reg': 1.9608435677762768, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100,},
    VIME: {
      'p_m': 0.1810075803617375, 'alpha': 2.7005666026932427, 'K': 3, 'beta': 0.20031952285751176
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 200, 'maxleaf': 128, 'loss_de': 3, 'loss_dr': 0.9},
    TabNet: {'n_d': 49, 'n_steps': 8, 'gamma': 1.031522844648987, 'cat_emb_dim': 2, 'n_independent': 1, 
              'n_shared': 4, 'momentum': 0.0015374105466576958, 'mask_type': 'entmax', 'n_a': 49, 
              'cat_idxs': [0], 'cat_dims': [3], 'device_name': device(type='cuda')},
    TabTransformer: {'dim': 256, 'depth': 2, 'heads': 2, 'weight_decay': -6, 'learning_rate': -3, 'dropout': 0},
    SAINT: {'dim': 32, 'depth': 1, 'heads': 2, 'dropout': 0.5},
  },
  Abalone: {
    RandomForest: {'max_depth': 9, 'n_estimators': 99},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 22, 'lambda_l1': 0.14257541971399731, 'lambda_l2': 0.00011586944753962882, 'learning_rate': 0.07245979023086785, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.21626767556712503, 'max_depth': 6, 'l2_leaf_reg': 21.130356608849873, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {'p_m': 0.8721504351545861, 'alpha': 3.038715869332491, 'K': 10, 'beta': 1.2414847045108695},
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 100, 'maxleaf': 128, 'loss_de': 2, 'loss_dr': 0.7},
    TabNet: {'n_d': 33, 'n_steps': 9, 'gamma': 1.8704976362400025, 'cat_emb_dim': 1, 'n_independent': 5, 
            'n_shared': 2, 'momentum': 0.1107777730479582, 'mask_type': 'entmax', 'n_a': 33, 'cat_idxs': [],
            'cat_dims': [], 'device_name': device(type='cuda')},
    TabTransformer: {'dim': 32, 'depth': 2, 'heads': 2, 'weight_decay': -2, 'learning_rate': -3, 'dropout': 0},
    SAINT: {'dim': 64, 'depth': 12, 'heads': 8, 'dropout': 0},
  },

  House_Sales: {
    RandomForest: {'max_depth': 9, 'n_estimators': 99},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 28, 'lambda_l1': 0.4107362779228514, 'lambda_l2': 1.3404325930803191e-07, 'learning_rate': 0.130249569345938, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.2089528671935541, 'max_depth': 8, 'l2_leaf_reg': 0.8697329291445745, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {
      'p_m': 0.5947367391828347, 'alpha': 0.5119049368440656, 'K': 2, 'beta': 0.22422357596955864
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 100, 'maxleaf': 64, 'loss_de': 3, 'loss_dr': 0.9},
    TabNet: {'n_d': 55, 'n_steps': 7, 'gamma': 1.4741351670576621, 'cat_emb_dim': 2, 'n_independent': 5, 
             'n_shared': 5, 'momentum': 0.35283418501370656, 'mask_type': 'entmax'},
    TabTransformer: {'dim': 32, 'depth': 6, 'heads': 4, 'weight_decay': -6, 'learning_rate': -3, 'dropout': 0.1},
    SAINT: {'dim': 128, 'depth': 12, 'heads': 8, 'dropout': 0},
  },
  MIP: {
    RandomForest: {'max_depth': 9, 'n_estimators': 99},
    XGBoost: {'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'},
    LightGBM: {'num_leaves': 45, 'lambda_l1': 0.00011964112931514078, 'lambda_l2': 1.1561747475283584e-07, 'learning_rate': 0.19036442097879416, 'verbosity': -1},
    CatBoost: {'learning_rate': 0.2682539692420618, 'max_depth': 2, 'l2_leaf_reg': 0.595594931273915, 'iterations': 100, 'od_type': 'Iter', 'od_wait': 20, 'verbose': 100},
    VIME: {
      'p_m': 0.7794279826211139, 'alpha': 1.8600788537267146, 'K': 15, 'beta': 0.10940866298283723
    },
    NODE: {'num_layers': 8, 'total_tree_count': 2048, 'tree_depth': 8, 'tree_output_dim': 3},
    DeepGBM: {'n_trees': 100, 'maxleaf': 64, 'loss_de': 3, 'loss_dr': 0.9},
    TabNet: {'n_d': 37, 'n_steps': 3, 'gamma': 1.6749039824525354, 'cat_emb_dim': 1, 'n_independent': 4, 
             'n_shared': 2, 'momentum': 0.2491546234839367, 'mask_type': 'entmax'},
    TabTransformer: {'dim': 128, 'depth': 6, 'heads': 8, 'weight_decay': -4, 'learning_rate': -3, 'dropout': 0.1},
    SAINT: {'dim': 32, 'depth': 3, 'heads': 2, 'dropout': 0},
  }
}
