parameters: {
  Boston: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  Socmob: {
    RandomForest: {},
    XGBoost: {
      'max_depth': 9, 
      'alpha': 0.00021827408412994793, 
      'lambda': 0.9948835376183525, 
      'eta': 0.014147235442426642, 
      'verbosity': 1, 
      #'tree_method': 'gpu_hist', 
      #'gpu_id': 0, 
      'objective': 'reg:squarederror', 
      'eval_metric': 'rmse'
    },
    LightGBM: {
      'num_leaves': 378, 
      'lambda_l1': 0.00017599402216123688, 
      'lambda_l2': 0.05689380362874709, 
      'learning_rate': 0.23855077406042233, 
      'verbosity': -1, 
      'objective': 'regression', 
      'metric': 'mse'},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  Sensory: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  Moneyball: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  Black_Friday: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  SAT11: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  Diamonds: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  House_Prices_Nominal: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  Mercedes_Benz: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  Allstate_Claims: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  Brazillian_Houses: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  Abalone: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  NYC_Taxi: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  House_Sales: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  },
  MIP: {
    RandomForest: {},
    XGBoost: {},
    LightGBM: {},
    CatBoost: {},
    VIME: {},
    NODE: {},
    DeepGBM: {},
    TabNet: {},
    TabTransformer: {},
    SAINT: {},
  }
}

