# General parameters
dataset: Brazillian_Houses
model_name: VIME # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM, ModelTree
                # MLP, TabNet, VIME, TabTransformer, RLN, DNFNet, STG, NAM, DeepFM, SAINT
objective: probabilistic_regression # Don't change (regression , probabilistic_regression)
# optimize_hyperparameters: True

y_distribution : quantile

# GPU parameters
use_gpu: True
gpu_ids: [0, 1]
data_parallel: False

# Optuna parameters - https://optuna.org/
n_trials: 100
direction: maximize  # maximize - class, minimize - reg

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221 # Don't change

# Preprocessing parameters
scale: True
target_encode: False
one_hot_encode: True
ordinal_encode : True

# Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 100
logging_period: 100

# About the data
num_classes: 1  # always 1 for regression
num_features: 12  #without target variable
nominal_idx : [0, 6] 
ordinal_idx : [7]
