# General parameters
dataset: House Prices Nominal
model_name: VIME # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM, ModelTree
                # MLP, TabNet, VIME, TabTransformer, RLN, DNFNet, STG, NAM, DeepFM, SAINT
objective: regression # Don't change
# optimize_hyperparameters: True

# GPU parameters
use_gpu: True
gpu_ids: [0, 1]
data_parallel: False

# Optuna parameters - https://optuna.org/
n_trials: 100
direction: minimize

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221 # Don't change

# Preprocessing parameters
scale: True
target_encode: False
one_hot_encode: True
ordinal_encode : True  #Set True if there is ordinal features

# Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 1000
logging_period: 100

# About the data
num_classes: 1  # always 1 for regression
num_features: 80  #without target variable
nominal_idx : [2, 7, 12]
ordinal_idx : [5,6,8,9,10,11,13,14,15,16,21,22,23,24,25,27,28,29,30,31,32,33,35,39,40,41,42,
                53,55,57,58,60,63,64,65,72,73,74,78,79]
dropna_idx : [0]
miss_cat_idx : [6, 25, 30, 31, 32, 33, 35, 42, 57, 58, 60, 
                63, 64, 72, 73, 74]
miss_num_idx : [3, 26, 59]

# cat_dims: will be automatically set.
#cat_dims: [9, 16, 7, 15, 6, 5, 2, 42]