parameters:
  Boston:
    MLP:
      d_block: 128
      d_in: 14
      d_out: 6
      dropout: 0.287804036106409
      n_blocks: 2
    ResMLP:
      d_block: 256
      d_hidden: 5
      d_hidden_multiplier: 4.696739338882331
      d_in: 14
      d_out: 6
      dropout1: 0.033619790667129355
      dropout2: 0.19699525336779936
      n_blocks: 3
  Brazillian_Houses:
    TabNet:
      cat_emb_dim: 2
      gamma: 1.8830178798654342
      mask_type: entmax
      momentum: 0.021221705429572718
      n_d: 35
      n_independent: 3
      n_shared: 5
      n_steps: 3
  Diamonds:
    TabNet:
      cat_emb_dim: 3
      gamma: 1.8437216964235192
      mask_type: entmax
      momentum: 0.12645427227434017
      n_d: 60
      n_independent: 5
      n_shared: 3
      n_steps: 3
  House_Prices_Nominal:
    SAINT:
      depth: 1
      dim: 128
      dropout: 0.7
      heads: 2
  House_Sales:
    ResMLP:
      d_block: 256
      d_hidden: 10
      d_hidden_multiplier: 2.2348878457541455
      d_in: 90
      d_out: 131
      dropout1: 0.141959826643883
      dropout2: 0.0504819732791219
      n_blocks: 6
    SAINT:
      depth: 6
      dim: 256
      dropout: 0.6
      heads: 8
  MIP:
    SAINT:
      depth: 3
      dim: 32
      dropout: 0.6
      heads: 2
  Sensory:
    MLP:
      d_block: 64
      d_in: 36
      d_out: 5
      dropout: 0.14268391486291263
      n_blocks: 6
    ResMLP:
      d_block: 64
      d_hidden: 8
      d_hidden_multiplier: 4.723144036923879
      d_in: 36
      d_out: 5
      dropout1: 0.2980643119373684
      dropout2: 0.07564863659722099
      n_blocks: 3
    VIME:
      K: 3
      alpha: 6.285259113099741
      beta: 1.7138736615322863
      p_m: 0.25864895183088943
