parameters:
  Abalone:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 1.0
      learning_rate: 0.1
      max_depth: 10
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/Abalone/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0e-08
      lambda_l2: 100.0
      learning_rate: 0.2
      metric: mse
      num_leaves: 16
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 10
      n_estimators: 100
    XGBoost:
      alpha: 0.01
      eta: 0.2
      eval_metric: rmse
      lambda: 100.0
      max_depth: 6
      objective: reg:squarederror
      verbosity: 1
  Black_Friday:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 5.0
      learning_rate: 0.2
      max_depth: 10
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/Black_Friday/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0e-08
      lambda_l2: 0.01
      learning_rate: 0.1
      metric: mse
      num_leaves: 64
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 12
      n_estimators: 100
    XGBoost:
      alpha: 0.01
      eta: 0.2
      eval_metric: rmse
      lambda: 100.0
      max_depth: 6
      objective: reg:squarederror
      verbosity: 1
  Boston:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 5.0
      learning_rate: 0.2
      max_depth: 6
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/Boston/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0e-08
      lambda_l2: 0.01
      learning_rate: 0.3
      metric: mse
      num_leaves: 32
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 12
      n_estimators: 50
    XGBoost:
      alpha: 0.01
      eta: 0.3
      eval_metric: rmse
      lambda: 0.01
      max_depth: 6
      objective: reg:squarederror
      verbosity: 1
  Brazillian_Houses:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 0.5
      learning_rate: 0.2
      max_depth: 10
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/Brazillian_Houses/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0e-08
      lambda_l2: 0.01
      learning_rate: 0.3
      metric: mse
      num_leaves: 64
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 12
      n_estimators: 5
    XGBoost:
      alpha: 1.0e-08
      eta: 0.3
      eval_metric: rmse
      lambda: 1.0e-08
      max_depth: 2
      objective: reg:squarederror
      verbosity: 1
  Diamonds:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 1.0
      learning_rate: 0.2
      max_depth: 10
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/Diamonds/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0
      lambda_l2: 1.0e-08
      learning_rate: 0.1
      metric: mse
      num_leaves: 128
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 12
      n_estimators: 100
    XGBoost:
      alpha: 1.0e-08
      eta: 0.1
      eval_metric: rmse
      lambda: 0.01
      max_depth: 6
      objective: reg:squarederror
      verbosity: 1
  House_Prices_Nominal:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 5.0
      learning_rate: 0.2
      max_depth: 6
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/House_Prices_Nominal/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0e-08
      lambda_l2: 1.0e-08
      learning_rate: 0.1
      metric: mse
      num_leaves: 6
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 10
      n_estimators: 50
    XGBoost:
      alpha: 0.01
      eta: 0.2
      eval_metric: rmse
      lambda: 0.01
      max_depth: 2
      objective: reg:squarederror
      verbosity: 1
  House_Sales:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 1.0
      learning_rate: 0.3
      max_depth: 6
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/House_Sales/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0
      lambda_l2: 1.0e-08
      learning_rate: 0.2
      metric: mse
      num_leaves: 16
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 12
      n_estimators: 20
    XGBoost:
      alpha: 0.01
      eta: 0.2
      eval_metric: rmse
      lambda: 0.01
      max_depth: 6
      objective: reg:squarederror
      verbosity: 1
  MIP:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 0.5
      learning_rate: 0.1
      max_depth: 2
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/MIP/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 0.01
      lambda_l2: 1.0
      learning_rate: 0.3
      metric: mse
      num_leaves: 256
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 12
      n_estimators: 100
    XGBoost:
      alpha: 1.0e-08
      eta: 0.3
      eval_metric: rmse
      lambda: 100.0
      max_depth: 6
      objective: reg:squarederror
      verbosity: 1
  Mercedes_Benz:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 30.0
      learning_rate: 0.3
      max_depth: 2
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/Mercedes_Benz/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0e-08
      lambda_l2: 100.0
      learning_rate: 0.2
      metric: mse
      num_leaves: 16
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 6
      n_estimators: 100
    XGBoost:
      alpha: 1.0e-08
      eta: 0.2
      eval_metric: rmse
      lambda: 100.0
      max_depth: 2
      objective: reg:squarederror
      verbosity: 1
  Moneyball:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 0.5
      learning_rate: 0.3
      max_depth: 2
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/Moneyball/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0e-08
      lambda_l2: 1.0
      learning_rate: 0.3
      metric: mse
      num_leaves: 6
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 10
      n_estimators: 100
    XGBoost:
      alpha: 1.0e-08
      eta: 0.2
      eval_metric: rmse
      lambda: 1.0e-08
      max_depth: 2
      objective: reg:squarederror
      verbosity: 1
  SAT11:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 5.0
      learning_rate: 0.2
      max_depth: 6
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/SAT11/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0
      lambda_l2: 1.0
      learning_rate: 0.3
      metric: mse
      num_leaves: 6
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 10
      n_estimators: 50
    XGBoost:
      alpha: 0.01
      eta: 0.3
      eval_metric: rmse
      lambda: 100.0
      max_depth: 6
      objective: reg:squarederror
      verbosity: 1
  Sensory:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 5.0
      learning_rate: 0.3
      max_depth: 6
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/Sensory/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 1.0e-08
      lambda_l2: 100.0
      learning_rate: 0.2
      metric: mse
      num_leaves: 2048
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 10
      n_estimators: 100
    XGBoost:
      alpha: 1.0e-08
      eta: 0.1
      eval_metric: rmse
      lambda: 0.01
      max_depth: 2
      objective: reg:squarederror
      verbosity: 1
  Socmob:
    CatBoost:
      iterations: 100
      l2_leaf_reg: 30.0
      learning_rate: 0.2
      max_depth: 10
      od_type: Iter
      od_wait: 20
      train_dir: output/CatBoost/Socmob/catboost_info
      verbose: 100
    LightGBM:
      lambda_l1: 0.01
      lambda_l2: 1.0
      learning_rate: 0.3
      metric: mse
      num_leaves: 256
      objective: regression
      verbosity: -1
    RandomForest:
      max_depth: 12
      n_estimators: 50
    XGBoost:
      alpha: 0.01
      eta: 0.3
      eval_metric: rmse
      lambda: 1.0e-08
      max_depth: 2
      objective: reg:squarederror
      verbosity: 1
