# General parameters
dataset: Sensory
model_name: VIME # LinearModel, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM, ModelTree
                # MLP, TabNet, VIME, TabTransformer, RLN, DNFNet, STG, NAM, DeepFM, SAINT
objective: regreprobabilistic_regressionssion # Don't change (regression , probabilistic_regression)
# optimize_hyperparameters: True

# GPU parameters
use_gpu: True
gpu_ids: [0, 1]
data_parallel: False

# Optuna parameters - https://optuna.org/
n_trials: 100
direction: minimize

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221 # Don't change

# Preprocessing parameters
scale: False
target_encode: False
one_hot_encode: True
ordinal_encode : False

# Training parameters
batch_size: 128
val_batch_size: 256
early_stopping_rounds: 20
epochs: 300
logging_period: 100

# About the data
num_classes: 1  # always 1 for regression
num_features: 11  #without target variable
nominal_idx : [0, 1, 2, 3,4,5,6,7,8,9,10]
# cat_dims: will be automatically set.
#cat_dims: [9, 16, 7, 15, 6, 5, 2, 42]