parameters:
  Socmob:
    ResMLP:
      d_block: 128
      d_hidden: 2
      d_hidden_multiplier: 2
      d_in: 39
      d_out: 9
      dropout1: 0.0
      dropout2: 0.3
      learning_rate: 1.0e-05
      n_blocks: 4
      weight_decay: 1.0e-06
